





class StringConstants{
 static String usingPolicyTitle ='Terms of use for using the platform for individual Hajj “NUSUK”.';
 static String usingPolicyIntro ='You agree by using NUSUK Platform (as defined below), you agree to be bound by the terms of use herein. Your consent in this regard is final and irrevocable, and you acknowledge that you have read, understood and agreed to the Terms of Use. \nThese terms of use aim to use the NUSUK platform to serve the Hajj and work to improve the services provided to Hajj and provide reservations for individual packages consisting of (flight / housing services / transportation services / catering services / services of a guide accompanying hajj / multiple payment services / verifying all documents required for all types of visas) and following up and supervising the relevant and competent authorities to enable them to continuously improve services and related procedures. We encourage you to read the terms and conditions for using the NUSUK platform here along with any other NUSUK platform policy and any other documents referred to here, so that you are fully aware. As part of our commitment to making the Platform a place you would like to visit frequently, we welcome all your comments and inquiries on any of the terms and conditions, policies or rules that we include from time to time.';
  static String usingPolicyDefinition = 'Terms of Use: \nThese are the terms of use for the use of the NUSUK platform.\nSVTS:\nIt is the Saudi Company for Visa and Travel Solutions and its subsidiaries, and it is a company authorized by the Ministry of Hajj and Umrah for the purposes of operating and developing the NUSUK platform for individual platform. (Collectively referred to as “we”, “our” or “us” or “Tasheer”)\n.NUSUK platform for individuals:\n(the “Platform”) It a platform that serves Hajj and provides individual packages consisting of services (flight / housing / transportation / subsistence / accompanying guide for pilgrims / multiple payments / verifying all documents and documents required for all types of visas) via the Internet between company and user.\nTarget countries:\nThose nations listed on the platform, which is periodically updated\n.User:\nAny Individuals who benefits is citizens and residents of the target countries from the services provided through the Platform, which requires the creation of a special account (the user is also referred to as “you”).\nServices: Online reservation services for individual packages for Hajj.\nCustomer: The natural person who benefits from the services provided through the platform\nVisa:\nIt is a electronic visa that allows the User to visit the Kingdom of Saudi ArabiaLaws of the Kingdom of Saudi Arabia: (the applicable law) any legally binding laws, regulations, or legislation including any legal article, cabinet decision, legal rule, regulation, circular, decree, administrative decision, treaty, charter, approvals, Exemptions, exceptions, amendments, orders, judgments and decisions, written interpretations, court decisions, licenses, publications, declarations or similar requirements of any Saudi government agency and any interpretation thereof that gives it the validity of the system by any Saudi government agency, Including any modifications, supplements, alternatives or other modifications made from time to time.\nGDPR:\nMeans regulations (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016.\nRelevant Data Protection Regulations: means all relevant data protection regulations (and/or amendments thereto) and any related regulations, statutory tools and the General Data Protection Regulation (GDPR), as applicable, in relation to data processing The user’s personal information and the freedom to transfer such personal data.';
}